# Generated by Django 4.2.9 on 2024-03-01 23:19

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0004_profile_dish1_profile_dish2_profile_dish3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Caribbean', 'Caribbean'), ('Central America', 'Central America'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], default='Asia', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='-', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='-', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cuisine_specialization',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instructions',
            field=djrichtextfield.models.RichTextField(default='-', max_length=20000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
