# Generated by Django 4.2.9 on 2024-03-04 12:30

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0007_alter_profile_dish1_alter_profile_dish2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Mobile Number'),
        ),
    ]
