# Generated by Django 4.2.9 on 2024-03-08 15:14

from django.db import migrations, models
import django_resized.forms
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='Please Enter Your Comment.', max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='Please Enter Your Email.', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(help_text='Please Enter Your Name.', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Caribbean', 'Caribbean'), ('Central America', 'Central America'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], default='Europe', help_text='Please specify your region.', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text='Please enter your city of residence (use abbreviations if its long).', max_length=12, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, help_text='Please enter your country of residence (use abbreviations if its long).', max_length=12, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cuisine_specialization',
            field=models.CharField(blank=True, help_text='Specify your cuisine & culinary expertise (e.g., Indian, Syrian, Italian).', max_length=25, null=True, verbose_name='Cuisine Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Please upload a photo of your culinary masterpiece', keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='dishes/', verbose_name='Dish Image-1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Please upload a photo of your culinary masterpiece', keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='dishes/', verbose_name='Dish Image-2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Please upload a photo of your culinary masterpiece', keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='dishes/', verbose_name='Dish Image-3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Please upload a photo of your culinary masterpiece', keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='dishes/', verbose_name='Dish Image-4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Please upload a photo of your culinary masterpiece', keep_meta=True, null=True, quality=75, scale=None, size=[600, 600], upload_to='dishes/', verbose_name='Dish Image-5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, help_text='You can enter a different email from the one used during registration.', max_length=50, null=True, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Please enter the URL of your Facebook account.', null=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male')], help_text='Please specify your gender.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', help_text='Please upload your profile picture.', keep_meta=True, null=True, quality=75, scale=None, size=[400, None], upload_to='profile/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Please enter the URL of your Instagram account.', null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(help_text='You can enter a different name from your username.', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Please provide your contact phone/mobile number.', max_length=25, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tiktok_link',
            field=models.URLField(blank=True, help_text='Please enter the URL of your Tiktok account.', null=True, verbose_name='Tiktok URL'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Please enter the URL of your Youtube channel.', null=True, verbose_name='Youtube URL'),
        ),
    ]
