# Generated by Django 4.2.9 on 2024-03-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0012_alter_comment_comment_alter_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Please provide your contact phone/mobile number.', max_length=25, null=True, verbose_name='Phone Number'),
        ),
    ]
