# Generated by Django 4.2.9 on 2024-03-09 12:37

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0013_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instructions',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=6000, null=True, verbose_name='Please Share Below Your Cook Instructions/Schedules'),
        ),
    ]
