# Generated by Django 4.2.9 on 2024-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0014_alter_profile_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cuisine_specialization',
            field=models.CharField(blank=True, help_text='Please specify one or two cuisines from your culinary expertise (e.g., Indian, Syrian, Italian)', max_length=25, null=True, verbose_name='Cuisine Type'),
        ),
    ]
