# Generated by Django 4.2.9 on 2024-03-09 23:13

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0015_alter_profile_cuisine_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Not Set', help_text='Please enter your city of residence (use abbreviations if its long).', max_length=12, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Not Set', help_text='Please enter your country of residence (use abbreviations if its long).', max_length=12, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cuisine_specialization',
            field=models.CharField(default='Not Set', help_text='Please specify one or two cuisines from your culinary expertise (e.g., Indian, Syrian, Italian)', max_length=25, verbose_name='Cuisine Type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Not Set', help_text='You can enter a different email from the one used during registration.', max_length=50, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Not Set', 'Not Set')], default='Not Set', help_text='Please specify your gender.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instructions',
            field=djrichtextfield.models.RichTextField(default='Not Set', max_length=6000, verbose_name='Please Share Below Your Cook Instructions/Schedules'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='Not Set', help_text='Please provide your contact phone/mobile number.', max_length=25, verbose_name='Phone Number'),
        ),
    ]
