# Generated by Django 5.1.7 on 2026-06-30 19:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chefs', '0017_alter_profile_city_alter_profile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Region',
            field=models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Caribbean', 'Caribbean'), ('Central America', 'Central America'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], default='Europe', help_text='Please specify your region.', max_length=20, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, help_text="Please enter your city of residence (use abbreviations if it's long).", max_length=12, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, help_text="Please enter your country of residence (use abbreviations if it's long).", max_length=12, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish1',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload a photo of your culinary masterpiece.', max_length=255, null=True, verbose_name='Dish Image-1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish2',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload a photo of your culinary masterpiece.', max_length=255, null=True, verbose_name='Dish Image-2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish3',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload a photo of your culinary masterpiece.', max_length=255, null=True, verbose_name='Dish Image-3'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish4',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload a photo of your culinary masterpiece.', max_length=255, null=True, verbose_name='Dish Image-4'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dish5',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload a photo of your culinary masterpiece.', max_length=255, null=True, verbose_name='Dish Image-5'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Not Set', 'Not Set')], default='Not Set', help_text='Please specify your gender.', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Please upload your profile picture.', max_length=255, null=True, verbose_name='Profile Picture'),
        ),
    ]
