# Generated by Django 4.2.9 on 2024-02-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_facebook_account_profile_instagram_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=1),
            preserve_default=False,
        ),
    ]
